### PR TITLE
updates for 2.1.0 release

### PR DESCRIPTION
**Pull request by nw**

### CODE REVIEW

**Comment by rosskukulinski** [comment]
@nw exciting!  Might be good to add a documentation section for migrating from earlier versions to this.  I see some ports have changes, so it's not as simple as just updating the `image` spec.

**Comment by nw** [comment]
@rosskukulinski thanks for taking a look!

While `console` default port did change, it does not effect the instructions on accessing the console because of the services abstraction. 

I do see your point but thought KISS might be appropriate here. We did not document migration from `1.x` to `2.x`. In order to delineate separation I was planning on retrofitting releases for prior versions.

**Comment by rosskukulinski** [comment]
Sure!  I guess I'm suggesting that people should `kubectl apply -f` to pull in the port changes instead of just updating the image.

**Comment by joemccann** [comment]
Can we merge this? I want to update dillinger.io on GCP but only if it's ready.

**Pull request merged**
